name: Test
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: experimental-github-action
      - name: Containerd and devmapper
        uses: yitsushi/experimental-github-action@main
      - name: Check
        run: |
          sudo ctr --debug plugin ls

          echo "::debug::Pull image with snapshotter"
          sudo ctr images pull --snapshotter devmapper docker.io/library/hello-world:latest

          echo "ctr --debug images ls"
          sudo ctr --debug images ls

          echo "ctr --debug snapshots ls"
          sudo ctr --debug snapshots ls

          echo "sudo ctr --debug snapshots --snapshotter=devmapper ls"
          sudo ctr --debug snapshots --snapshotter=devmapper ls
